# Spring will read environment variables from Render.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# Disable Redis in production
spring.cache.type=none

# JWT
secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}